<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/10_BCELossipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
out = torch.randn(10)
real = torch.rand(10)

In [ ]:
out , real

(tensor([ 0.1463,  0.4132, -0.5091,  1.4223, -1.4767,  0.0546, -1.6801,  1.1652,
          0.1132, -0.1578]),
 tensor([0.1628, 0.5597, 0.5420, 0.3560, 0.8572, 0.9082, 0.1062, 0.8625, 0.2451,
         0.5024]))

In [ ]:
act_out = nn.Sigmoid()(out)
nn.BCELoss(reduction = 'none')(act_out , real)

tensor([0.7451, 0.6897, 0.7466, 1.1320, 1.4716, 0.6712, 0.3492, 0.4317, 0.7236,
        0.6966])

In [ ]:
(-(real * torch.log(act_out) + (1 - real) * torch.log(1 - act_out)))

tensor([0.7451, 0.6897, 0.7466, 1.1320, 1.4716, 0.6712, 0.3492, 0.4317, 0.7236,
        0.6966])

In [ ]:
act_out = nn.Sigmoid()(out)
nn.BCELoss(reduction = 'sum')(act_out , real)

tensor(8.5863)

In [ ]:
(-(real * torch.log(act_out) + (1 - real) * torch.log(1 - act_out))).sum()

tensor(8.5863)

In [ ]:
act_out = nn.Sigmoid()(out)
nn.BCELoss(reduction = 'mean')(act_out , real)

tensor(0.8586)

In [ ]:
(-(real * torch.log(act_out) + (1 - real) * torch.log(1 - act_out))).mean()

tensor(0.8586)

In [ ]:
act_out = nn.Sigmoid()(out)
wts = torch.zeros(10)
wts[0] = -2
wts[5] = 1
nn.BCELoss(weight = wts , reduction = 'none')(act_out , real)

tensor([-1.4903,  0.0000,  0.0000,  0.0000,  0.0000,  0.6712,  0.0000,  0.0000,
         0.0000,  0.0000])