<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/11_crossentropyloss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
#reduction
out = torch.randn(5)
inds = torch.Tensor([2]).long()

In [ ]:
out , inds

(tensor([ 0.6943,  0.3898,  0.1563,  1.7468, -0.8538]), tensor([2]))

In [ ]:
out.shape , inds.shape

(torch.Size([5]), torch.Size([1]))

In [ ]:
inds.squeeze()

tensor(2)

In [ ]:
nn.CrossEntropyLoss(reduction = 'none')(out , inds.squeeze())

tensor(2.2241)

In [ ]:
torch.exp(out)

tensor([2.0023, 1.4766, 1.1692, 5.7360, 0.4258])

In [ ]:
temp = torch.exp(out)
-torch.log(temp[2] / temp.sum())

tensor(2.2241)

In [ ]:
nn.CrossEntropyLoss(reduction = 'none' , ignore_index = 0)(out , inds.squeeze())

tensor(2.2241)

In [ ]:
#Weights
out = torch.randn(9 , 10)
inds = torch.multinomial(torch.ones(10) , 9 , replacement = True)

In [ ]:
out , inds

(tensor([[-0.6627,  0.0125, -0.8689,  1.2663,  0.3835, -0.2469,  0.7033,  0.8755,
           0.2038, -0.1871],
         [ 0.3090, -1.8333,  0.6941, -1.2738,  1.0952,  0.7026,  1.0573, -0.8585,
          -0.1993,  0.8612],
         [-1.2767,  1.2989, -0.7341,  0.1380,  0.8725,  0.0437,  0.7737,  0.1586,
           1.2480,  0.3353],
         [ 1.0488,  1.8165, -0.8610, -0.0161, -1.7292,  1.1800,  0.9108,  0.6373,
           0.7313, -0.2089],
         [-0.4451,  0.3147, -0.0676,  0.1944, -0.6609,  0.0896, -2.0779,  0.0921,
           1.8691,  1.6468],
         [-0.6787, -0.3080,  0.3943,  0.7603, -0.0178,  0.4185, -0.5894,  0.0299,
           1.4921, -2.2774],
         [-0.7358, -0.3268,  0.4810,  0.0871, -0.0615,  0.2411,  0.0348,  0.2545,
           1.0046,  0.9578],
         [-0.3820, -0.1468,  0.0317,  0.6966,  0.3108,  0.5899, -1.2950,  0.4363,
          -0.2209,  1.4802],
         [ 0.2837, -0.7945, -0.3992,  0.8614, -0.4167,  1.2429, -0.9311,  1.2213,
          -0.9615,  0.9733]]),

In [ ]:
wt = torch.ones(10)
wt[torch.arange(5)*2] *= 2
wt

tensor([2., 1., 2., 1., 2., 1., 2., 1., 2., 1.])

In [ ]:
[torch.arange(4)*2]

[tensor([0, 2, 4, 6])]

In [ ]:
nn.CrossEntropyLoss(reduction = 'none')(out , inds)

tensor([3.4603, 3.4234, 2.7970, 1.3594, 2.1483, 2.6299, 2.9093, 3.4872, 2.0821])

In [ ]:
nn.CrossEntropyLoss(weight = wt , reduction = 'none')(out , inds)

tensor([6.9206, 6.8469, 5.5940, 2.7187, 2.1483, 2.6299, 2.9093, 3.4872, 2.0821])

In [ ]:
#Label smoothing

In [ ]:
ohe = torch.zeros(10)
ohe[2] = 1
ohe

tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
alpha = 0.2

In [ ]:
(1 - alpha) * ohe + alpha / 10

tensor([0.0200, 0.0200, 0.8200, 0.0200, 0.0200, 0.0200, 0.0200, 0.0200, 0.0200,
        0.0200])

In [ ]:
((1 - alpha) * ohe + alpha / 10).sum()

tensor(1.0000)

In [ ]:
nn.CrossEntropyLoss(label_smoothing = 0.1 , reduction = 'none')(out , inds)

tensor([3.3774, 3.3651, 2.7620, 1.4877, 2.2456, 2.6280, 2.8801, 3.4268, 2.1380])