<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/12_crossentropyloss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
#reduction
out = torch.randn(5)
inds = torch.Tensor([2]).long()

In [ ]:
out , inds

(tensor([ 0.9024, -0.1498,  0.7076, -0.9631,  0.8030]), tensor([2]))

In [ ]:
out.shape , inds.shape

(torch.Size([5]), torch.Size([1]))

In [ ]:
inds.squeeze()

tensor(2)

In [ ]:
nn.CrossEntropyLoss(reduction = 'none')(out , inds.squeeze())

tensor(1.3680)

In [ ]:
torch.exp(out)

tensor([2.4656, 0.8609, 2.0292, 0.3817, 2.2323])

In [ ]:
temp = torch.exp(out)
-torch.log(temp[2] / temp.sum())

tensor(1.3680)

In [ ]:
nn.CrossEntropyLoss(reduction = 'none' , ignore_index = 0)(out , inds.squeeze())

tensor(1.3680)

In [ ]:
#Weights
out = torch.randn(9 , 10)
inds = torch.multinomial(torch.ones(10) , 9 , replacement = True)

In [ ]:
out , inds

(tensor([[ 0.6772,  0.4433, -0.4912,  0.3349, -0.1015,  0.1177, -0.7259,  0.7339,
          -0.0702, -1.4057],
         [ 0.1097,  0.9219, -0.6161,  1.3091, -0.6149, -0.2227, -1.3919,  0.1936,
           2.1101, -0.2448],
         [-0.5351,  1.0995, -0.6357, -0.4167, -0.0315,  0.5928,  1.3591,  1.0082,
          -0.3696,  0.3843],
         [-0.5452, -1.0055,  1.6350, -0.2632,  0.8416,  0.6649,  1.1866, -0.5104,
          -1.3072,  0.4845],
         [ 0.0605, -1.4296, -2.8557,  0.0629, -0.1547,  0.1555, -0.3099, -1.6775,
          -0.6627, -0.4867],
         [ 1.0061, -1.4418, -0.1930,  0.0746, -1.2188, -0.9010, -1.4402,  0.2854,
          -1.3378,  1.3713],
         [ 1.1425, -0.7146, -2.1607,  1.2830, -2.1354,  0.8564,  1.1022, -0.3680,
           2.3558,  1.1227],
         [-0.3292, -0.8464, -0.4046,  1.4260, -1.6964, -0.0087, -0.4248, -1.6259,
          -0.4797,  1.6715],
         [-1.5298,  1.4272,  0.5103,  2.0009, -2.9358,  0.3441,  0.5443, -0.5978,
           1.5245, -1.0864]]),

In [ ]:
wt = torch.ones(10)
wt[torch.arange(5)*2] *= 2
wt

tensor([2., 1., 2., 1., 2., 1., 2., 1., 2., 1.])

In [ ]:
[torch.arange(5) * 2]

[tensor([0, 2, 4, 6, 8])]

In [ ]:
nn.CrossEntropyLoss(reduction = 'none')(out , inds)

tensor([1.9823, 1.6719, 2.2013, 3.0892, 2.0265, 2.6218, 0.9453, 3.4813, 2.5859])

In [ ]:
nn.CrossEntropyLoss(weight = wt , reduction = 'none')(out , inds)

tensor([1.9823, 1.6719, 2.2013, 3.0892, 4.0529, 5.2436, 1.8905, 3.4813, 5.1718])

In [ ]:
#Label smoothing

In [ ]:
ohe = torch.zeros(10)
ohe[2] = 1
ohe

tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
alpha = 0.2

In [ ]:
(1 - alpha) * ohe + alpha / 10

tensor([0.0200, 0.0200, 0.8200, 0.0200, 0.0200, 0.0200, 0.0200, 0.0200, 0.0200,
        0.0200])

In [ ]:
((1 - alpha) * ohe + alpha / 10).sum()

tensor(1.0000)

In [ ]:
nn.CrossEntropyLoss(label_smoothing = 0.1 , reduction = 'none')(out , inds)

tensor([2.0315, 1.7873, 2.2360, 3.0511, 2.0840, 2.6405, 1.1560, 3.4239, 2.6349])