<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/13_14_15conv2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

Zero padding

In [ ]:
img1 = torch.arange(1 , 10).reshape(1 , 1 , 3 , 3)

In [ ]:
img1

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [ ]:
nn.functional.pad(img1 , (1 , 1 , 1 , 1) , 'constant' , 0)

tensor([[[[0, 0, 0, 0, 0],
          [0, 1, 2, 3, 0],
          [0, 4, 5, 6, 0],
          [0, 7, 8, 9, 0],
          [0, 0, 0, 0, 0]]]])

In [ ]:
nn.functional.pad(img1 , (1 , 1 , 1 , 1) , 'constant' , 0).shape

torch.Size([1, 1, 5, 5])

Reflective Padding

In [ ]:
img2 = torch.arange(1 , 10).reshape(1 , 1 , 3 , 3)

In [ ]:
img2

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [ ]:
nn.functional.pad(img2 , (2 , 2 , 2 , 2) , 'reflect')

tensor([[[[9, 8, 7, 8, 9, 8, 7],
          [6, 5, 4, 5, 6, 5, 4],
          [3, 2, 1, 2, 3, 2, 1],
          [6, 5, 4, 5, 6, 5, 4],
          [9, 8, 7, 8, 9, 8, 7],
          [6, 5, 4, 5, 6, 5, 4],
          [3, 2, 1, 2, 3, 2, 1]]]])

In [ ]:
nn.functional.pad(img2 , (2 , 2 , 2 , 2) , 'reflect').shape

torch.Size([1, 1, 7, 7])

Replication padding

In [ ]:
img3 = torch.arange(1 , 10).reshape(1 , 1 , 3 , 3)

In [ ]:
nn.functional.pad(img3 , (2 , 2 , 2 , 2) , 'replicate')

tensor([[[[1, 1, 1, 2, 3, 3, 3],
          [1, 1, 1, 2, 3, 3, 3],
          [1, 1, 1, 2, 3, 3, 3],
          [4, 4, 4, 5, 6, 6, 6],
          [7, 7, 7, 8, 9, 9, 9],
          [7, 7, 7, 8, 9, 9, 9],
          [7, 7, 7, 8, 9, 9, 9]]]])

In [ ]:
nn.functional.pad(img3 , (2 , 2 , 2 , 2) , 'replicate').shape

torch.Size([1, 1, 7, 7])

Circular padding

In [ ]:
img4 = torch.arange(1 , 10).reshape(1 , 1 , 3 , 3)

In [ ]:
nn.functional.pad(img3 , (2 , 2 , 2 , 2) , 'circular')

tensor([[[[5, 6, 4, 5, 6, 4, 5],
          [8, 9, 7, 8, 9, 7, 8],
          [2, 3, 1, 2, 3, 1, 2],
          [5, 6, 4, 5, 6, 4, 5],
          [8, 9, 7, 8, 9, 7, 8],
          [2, 3, 1, 2, 3, 1, 2],
          [5, 6, 4, 5, 6, 4, 5]]]])

In [ ]:
nn.functional.pad(img3 , (2 , 2 , 2 , 2) , 'circular').shape

torch.Size([1, 1, 7, 7])

Convolution operation

In [ ]:
m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))

In [ ]:
inp = torch.randn(20, 16, 50, 100)

In [ ]:
output = m(inp)

In [ ]:
output.shape

torch.Size([20, 33, 26, 100])

In [ ]:
((50 + 2 * 4 - 3 * (3 - 1) - 1) / 2) + 1

26.5

In [ ]:
((100 + 2 * 2 - 1 * (5 - 1) - 1) / 1) + 1

100.0