<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/17_ConvTranspose2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
inp = torch.Tensor([[[[2 , 3 , 1] ,
                      [0 , 4 , 2] ,
                      [1 , 6 , 7]]]])

kernel = torch.Tensor([[[[1 , 2] ,
                         [3 , 4]]]])

In [ ]:
padding = 0
stride = 1
out1 = nn.functional.conv_transpose2d(inp, kernel, stride=stride, padding=padding)

In [ ]:
out1

tensor([[[[ 2.,  7.,  7.,  2.],
          [ 6., 21., 25.,  8.],
          [ 1., 20., 41., 22.],
          [ 3., 22., 45., 28.]]]])

In [ ]:
padding = 0
stride = 2
out2 = nn.functional.conv_transpose2d(inp, kernel, stride=stride, padding=padding)

In [ ]:
out2

tensor([[[[ 2.,  4.,  3.,  6.,  1.,  2.],
          [ 6.,  8.,  9., 12.,  3.,  4.],
          [ 0.,  0.,  4.,  8.,  2.,  4.],
          [ 0.,  0., 12., 16.,  6.,  8.],
          [ 1.,  2.,  6., 12.,  7., 14.],
          [ 3.,  4., 18., 24., 21., 28.]]]])

In [ ]:
padding = 2
stride = 2
out3 = nn.functional.conv_transpose2d(inp, kernel, stride=stride, padding=padding)

In [ ]:
out3

tensor([[[[ 4.,  8.],
          [12., 16.]]]])

In [ ]:
padding = 0
output_padding = 1
stride = 2
out4 = nn.functional.conv_transpose2d(inp, kernel, stride=stride, padding=padding , output_padding = output_padding)

In [ ]:
out4

tensor([[[[ 2.,  4.,  3.,  6.,  1.,  2.,  0.],
          [ 6.,  8.,  9., 12.,  3.,  4.,  0.],
          [ 0.,  0.,  4.,  8.,  2.,  4.,  0.],
          [ 0.,  0., 12., 16.,  6.,  8.,  0.],
          [ 1.,  2.,  6., 12.,  7., 14.,  0.],
          [ 3.,  4., 18., 24., 21., 28.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

In [ ]:
padding = 0
stride = 2
dilation = 1
out5 = nn.functional.conv_transpose2d(inp, kernel, stride=stride, padding=padding , dilation = dilation)

In [ ]:
out5

tensor([[[[ 2.,  4.,  3.,  6.,  1.,  2.],
          [ 6.,  8.,  9., 12.,  3.,  4.],
          [ 0.,  0.,  4.,  8.,  2.,  4.],
          [ 0.,  0., 12., 16.,  6.,  8.],
          [ 1.,  2.,  6., 12.,  7., 14.],
          [ 3.,  4., 18., 24., 21., 28.]]]])