<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/17_maxpool2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
img = torch.arange(1 , 26).reshape(1 , 1 , 5 , 5)

In [ ]:
img

tensor([[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20],
          [21, 22, 23, 24, 25]]]])

In [ ]:
nn.functional.max_pool2d(img , kernel_size = 2 , ceil_mode = True , return_indices = True)

(tensor([[[[ 7,  9, 10],
           [17, 19, 20],
           [22, 24, 25]]]]),
 tensor([[[[ 6,  8,  9],
           [16, 18, 19],
           [21, 23, 24]]]]))

In [ ]:
nn.functional.max_pool2d(img , kernel_size = 2)