<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/3_relu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [ ]:
rand1 = torch.randn(10)

In [ ]:
rand1

tensor([-1.3494,  0.5721, -0.4710,  1.1396,  0.6859, -0.5445, -1.1971, -0.7275,
         0.5055,  0.2035])

In [ ]:
nn.ReLU()(rand1)

tensor([0.0000, 0.5721, 0.0000, 1.1396, 0.6859, 0.0000, 0.0000, 0.0000, 0.5055,
        0.2035])

In [ ]:
rand1

tensor([-1.3494,  0.5721, -0.4710,  1.1396,  0.6859, -0.5445, -1.1971, -0.7275,
         0.5055,  0.2035])