<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/5_sigmoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
rand = torch.randn(10)

In [ ]:
rand

tensor([-1.6226,  0.3356, -0.1958, -0.2957, -0.8530, -0.2548, -2.8636, -1.4031,
         1.1976, -1.5322])

In [ ]:
nn.Sigmoid()(rand)

tensor([0.1649, 0.5831, 0.4512, 0.4266, 0.2988, 0.4366, 0.0540, 0.1973, 0.7681,
        0.1777])

In [ ]:
def custom_sig(l):
  return 1 / (1 + torch.exp(-l))

In [ ]:
custom_sig(rand)

tensor([0.1649, 0.5831, 0.4512, 0.4266, 0.2988, 0.4366, 0.0540, 0.1973, 0.7681,
        0.1777])