<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/6_tanh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
rand = torch.randn(10)

In [ ]:
rand

tensor([ 1.4298, -1.1074,  0.2768, -0.0492, -0.0194, -0.1840,  1.3149, -0.4361,
        -0.0043, -0.1168])

In [ ]:
nn.Tanh()(rand)

tensor([ 0.8916, -0.8031,  0.2700, -0.0491, -0.0194, -0.1819,  0.8655, -0.4104,
        -0.0043, -0.1163])

In [ ]:
def custom_tanh(x):
  num = torch.exp(x) - torch.exp(-x)
  dem = torch.exp(x) + torch.exp(-x)
  return num / dem

In [ ]:
custom_tanh(rand)

tensor([ 0.8916, -0.8031,  0.2700, -0.0491, -0.0194, -0.1819,  0.8655, -0.4104,
        -0.0043, -0.1163])