<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/8_L1Loss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
out = torch.randn(10)
target = torch.randn(10)

In [ ]:
out , target

(tensor([-0.9781, -1.3906, -0.0423, -0.4269,  0.9083, -1.5137,  1.0014,  0.4989,
          0.1595, -0.4994]),
 tensor([-1.8195,  0.5380,  0.7052, -0.1487, -0.8891,  1.1160,  0.6511,  0.7737,
          0.5940,  0.8579]))

In [ ]:
nn.L1Loss(reduction = 'none')(out , target)

tensor([0.8415, 1.9287, 0.7475, 0.2783, 1.7975, 2.6297, 0.3503, 0.2749, 0.4345,
        1.3573])

In [ ]:
torch.abs(out - target)

tensor([0.8415, 1.9287, 0.7475, 0.2783, 1.7975, 2.6297, 0.3503, 0.2749, 0.4345,
        1.3573])

In [ ]:
nn.L1Loss(reduction = 'sum')(out , target)

tensor(7.8717)

In [ ]:
torch.abs(out - target).sum()

tensor(7.8717)

In [ ]:
nn.L1Loss(reduction = 'mean')(out , target)

tensor(0.7872)

In [ ]:
torch.abs(out - target).mean()

tensor(0.7872)