<a href="https://colab.research.google.com/github/DatumLearning/PyTorch_functions/blob/main/9_MSELoss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
out = torch.randn(10)
target = torch.randn(10)

In [ ]:
out , target

(tensor([ 0.6892, -0.2860, -0.0096,  0.4027, -0.1802, -0.5634, -1.4514,  0.5956,
          0.2113,  0.0068]),
 tensor([ 0.8245, -0.6872, -0.3566, -0.2669, -0.4937,  1.3047, -0.5157,  0.8484,
          0.3413, -0.4652]))

In [ ]:
nn.MSELoss(reduction = 'none')(out , target)

tensor([0.0183, 0.1609, 0.1205, 0.4484, 0.0983, 3.4897, 0.8756, 0.0639, 0.0169,
        0.2228])

In [ ]:
(out - target) ** 2

tensor([0.0183, 0.1609, 0.1205, 0.4484, 0.0983, 3.4897, 0.8756, 0.0639, 0.0169,
        0.2228])

In [ ]:
nn.MSELoss(reduction = 'sum')(out , target)

tensor(5.5152)

In [ ]:
((out - target) ** 2).sum()

tensor(5.5152)

In [ ]:
nn.MSELoss(reduction = 'mean')(out , target)

tensor(0.5515)

In [ ]:
((out - target) ** 2).mean()

tensor(0.5515)